[package]
name = "image_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
image = "0.24.5"
imageproc = "0.23.0"
rusttype = "0.9.3"
tinysegmenter = "0.1"
